### ISSUE TITLE
Investigate  GlobalEventExecutorTest.testAutomaticStartStop test failure

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#5551]
Failed on CI:

```
java.lang.AssertionError: 
Expected: sameInstance(<Thread[globalEventExecutor-2-6,5,]>)
     but: was <Thread[globalEventExecutor-2-7,5,main]>
java.lang.AssertionError: 

Expected: sameInstance(<Thread[globalEventExecutor-2-6,5,]>)
     but: was <Thread[globalEventExecutor-2-7,5,main]>
```
